### ISSUE TITLE
Other Data and Events from CV Pilots - How to relate relevant BSMs. 

### ISSUE THREAD

**Issue by micbarton** [usdot-its-jpo-data-portal/sandbox#1]
I like the directory structure of {Data_Type}/{Year}/{Month}/{Day}/{Hour}. I'm thinking how events, as requested by a state DOT such as when FCW is displayed to driver, will fit this structure.  I would like to be able to find an event and then easily locate the paths (from the BSMs) of vehicles involved and determine the vehicle kinematics for those involved.  Possibly you could provide an example, or explain proposed structuring, of how the path of one vehicle can be extracted from all the hundreds of other vehicles that are providing BSMs to the BSM directories. Same holds for TIMs. We would like to analyze when the time was received, when it was displayed to the driver, and when he possibly reacted to the information.

**Comment by jlarkin** [comment]
Thank you for your feedback.  Having another level down with the event messages may be useful and something we will consider in the future.
 
In the BSM files, events are flagged based on the J2735 standard as key items that happen in the vehicle like abs brakes firing, and will not include things like when Forward Collision Warning (FCW) fires.  FCW warnings are controlled by the application in the On-Board Unit (OBU) within the car and depend on the application settings.  You will not be able to get that information from BSM messages.  You could, however, review the data for distance to other vehicles and if hard breaking is done to try and evaluate the best time for FCW to go off.
 
Please also remember that current WYDOT data is still in testing and will not be in production until later this year.  This means that some of the data may be generated with braking data to test the system and may not be real hard braking scenarios.

**Comment by micbarton** [comment]
Thanks, I am just getting familiar with this idea of public-access. So it will be interesting to see how the Tampa Pilot handles distributing this 'extra' data that I mentioned along with the more normal types of J2735 pilot data you mentioned. It will be great if this data-portal works out to be a 'one stop shop' for all pilot data which I understand is the intention. That would make analysis efficient since consistency of access and arrangement would be the same for all v2v pilot sites.
