### ISSUE TITLE
An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist

### ISSUE THREAD

**Issue by shilezhang** [usdot-its-jpo-data-portal/sandbox#18]

**Comment by shilezhang** [comment]
Hi 

I got this error.

Can anyone pls help? Is the data/bucket removed?

**Comment by shahriar0651** [comment]
It seems the bucket name is `usdot-its-cvpilot-publicdata` but in the instruction, it says `usdot-its-cvpilot-public-data` with an extra hyphen. Replacing {bucket name} with `usdot-its-cvpilot-publicdata` should work.
