### ISSUE TITLE
Access Denied: Not able to download BSM dataset 2018.

### ISSUE THREAD

**Issue by PrinkleSharma** [usdot-its-jpo-data-portal/sandbox#2]
While trying to download the complete BSM dataset from S3 Bucket using AWS CLI, an error is encountered "An error occurred (AccessDenied) when calling the GetObject operation: Access Denied". Tried downloading from web interface too, but no success. No such issue came up while downloading 2017 BSM data (which has data from 01/18/2018).

**Comment by James-OHara** [comment]
Hi,

This is a known issue we are actively working to resolve. We should have a solution shortly and will update this issue when that occurs. 

Thanks!

**Comment by James-OHara** [comment]
This issue has been resolved and all data on the sandbox should be downloadable.
