### ISSUE TITLE
Replace CVPEP with SDC link

### ISSUE THREAD

**Issue by arielsgold** [usdot-its-jpo-data-portal/sandbox#3]
CVPEP has been folded into https://github.com/usdot-jpo-sdc -- please update reference/link

**Comment by chuehlien** [comment]
Reference and link to CVPEP has been updated to SDC. Please close the issue if the change is satisfactory. Thanks!

Commit: https://github.com/usdot-its-jpo-data-portal/sandbox/commit/0d14ace6483c855a72d138f8713dc175d431ef9f
File: https://github.com/usdot-its-jpo-data-portal/sandbox#related-its-jpo-projects

**Comment by hmusavi** [comment]
@arielsgold ,

Please review the documentation and if the issue has been addressed to your satisfaction, close the issue to indicate your approval of the changes.

Thanks,
DataHub Team
